### ISSUE TITLE
Can't Switch Between QMs on Tablet

### ISSUE THREAD

**Issue by FoodIsLogical** [sjcbulldog/elescout#21]
After assigning a tablet number to a tablet, you get spawned into a QM and then cannot click into a different match from there.

**Comment by sjcbulldog** [comment]
This was a problem where the logic was changed to be sure latest scouting results were gathered from the tablet.  This caused an infinite loop on the scouting tablet causing menus to work very slowly and nothing else to really work.  This logic has been reworked to prevent this issue.
