### ISSUE TITLE
Syncing a physical tablet when the xeroscout version of it already has data

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#22]
When syncing a tablet but there is already data for the team it should be scouting 2 things happen that shouldn't:
1. The form doesn't show what data was originally inputted, rather it shows an unfilled copy of the scouting form
2. The menu options file, options, and view can be opened preventing the tablet from being synced

**Comment by FoodIsLogical** [comment]
We tried with a new event that doesn't have previous data- exact same issues happen

**Comment by sjcbulldog** [comment]
I think this was the same freezing issue with scouting tablets.  Lets try this again at the next meeting.

**Comment by AarushPalve** [comment]
Issue doesn't persist on new version
