### ISSUE TITLE
Shorting randomly generated text

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#23]
When randomly generating data in for an event can you make all the textboxes have "note" as their data instead of 0-255 random characters?

**Comment by sjcbulldog** [comment]
The data is between 8 and the max length for that field.  Making it note is not meaninful as next year will not be notes.  Keep in mind this program is independent of specific year of the game.  All game specific data comes from the scouting form or from the blue alliance (score breakdown).  Do you want a limit to the data length for random data of something less than the maxlen for a given field (e.g. between 4 - 12).l

**Comment by AarushPalve** [comment]
I just meant for the autogen shortcut (asdf hold) the data should fill as “note” rather then a bunch of random characters to improve usability.
-Aarush

**Comment by sjcbulldog** [comment]
I will shorten the data but keep it random.  Note is specific to a given year and I don't want anything tied to a specific year

**Comment by sjcbulldog** [comment]
I added a set of relatively short words for the text (less than 12 characters) and then select from between them.
