### ISSUE TITLE
Synced TBA/Statbotics data appends itself to the front of the match data view

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#24]
Can you make it so that the aforementioned data attaches after all the scouting data rather than before?

**Comment by sjcbulldog** [comment]
The data was placed into a sqlite3 database.  The ordering of data in this database is arbitrary.  The data must be ordered when extracted from the database so I have added this.  The order of the data is ...

1. The initial data columns to create the table.
2. The data columns extracted from the blue alliance to create the tables.
3. The data columns extracted from the forms
4. The data columns from importing additional blue alliance/statbotics data
