### ISSUE TITLE
Scouting tablet screen refresh

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#25]
Sometimes the view just breaks (like the picture you showed) and when prompted you said it had something to do with the screen refresh on the tablets

**Comment by AarushPalve** [comment]
The screen only refreshed the spots where touch input is giver

**Comment by sjcbulldog** [comment]
This is likely the one bug where the scouting tablet code locked up in a tight loop and did not allow other things to run.  This meant the refresh code did not run and could not referesh the screen.  Lets try again next meeting.

**Comment by AarushPalve** [comment]
The issue showed up again and it seems to have to so with the view menue. Since you are planning on removing that before the season this should be a non-issue but its best to document these things.
