### ISSUE TITLE
QOL for sync view

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#26]
On sync view can you make it so instead of the tablet column having "tablet 1" as its data it has #1 (whatever the tablet number is).

**Comment by sjcbulldog** [comment]
What is displayed is the tablet name.  The tablets have names, we just happen to make these names 'Tablet 1' in the screen where table names are auto assigned.

**Comment by sjcbulldog** [comment]
I am closing this.  Tablet names are better than tablet numbers.  Displaying the tablet name is the right thing.
