### ISSUE TITLE
Live picklist

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#3]
Ideally, there would be a tab in Xero Central where I could manually sort teams. It would function like an Excel sheet and in the unused columns I could add an average value for any piece of scouted data. Ie I could have Number, name, av speaker, drivebase, av amp, etc... as my collumns.

**Comment by sjcbulldog** [comment]
The initial version of the pick list is done.  It will probably need to be improved, but the initial version is available.  I will close this item and we will add more specific issues to improve it going forward.
