### ISSUE TITLE
Autonomous Data Not Transferring After Reversing Screen

### ISSUE THREAD

**Issue by FoodIsLogical** [sjcbulldog/elescout#34]
Tried: Added to speaker counter and clicked on notes, then reversed the screen and clicked back into the same match
Expected: Previously added data regenerates, and only the reversing of the field layout would change
Shown: After reversing the view, the layout successfully reversed but the autonomous form reset so that no previously recorded data transferred

**Comment by sjcbulldog** [comment]
This was an issue with storing the data stored in the form when the reverse command was executed.  Since the reverse command clears the form, if the reverse command does not store the data in the form, it is lost.  This is now fixed.
