### ISSUE TITLE
Note 3-5 (auto) don't show up for team graph

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#35]
Tried: Making an auto graph that has all the relevent data
Expected: to see notes 3, 4, and 5 in the Left and Right match fields dropdown
Result: Didn't see them (notes 1, 2, 7 and 8 still are visible).

**Comment by AarushPalve** [comment]
They are Booleans btw

**Comment by sjcbulldog** [comment]
They are there but the order is funny.  Those three are near the end of the list and not with the other fields.  I now sort the fields so they fields will be easier to find.
