### ISSUE TITLE
Undo sort button for picklist

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#41]
Its easy to accidentally press sort and lose your picklist order so having an undo button would be very helpful

**Comment by sjcbulldog** [comment]
I am not sure what you mean.  If you sort by any other column, you can just sort again by the Rank columns which is the order of your pick list.  The Rank column only changes values (rank association with a team) when you drag and drop a team on the pick list.  So, if you accidently sort by a column, just sort again by the Rank columns to get back to the picklist order.,
