### ISSUE TITLE
Syncing xerosocut on the same device that XeroCentral doesn't work

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#43]
Tried: File-> Sync (TCP) | After resetting tablet
Expected: Tablet to sync and work as a local scouting tablet instance
Result: Error Synchronizing - connect ETIMEDOUT 192.168.1.1:45455

**Comment by sjcbulldog** [comment]
What does 'local' mean?

**Comment by AarushPalve** [comment]
I meant local as a way to indicate it was on the same device as Xero Central-should have made that more clear

**Comment by sjcbulldog** [comment]
Again, I don't understand this.  You really need to type more words to explain what is happening.  What is a local scouting instance?  Do you mean you tried to run the scouting app on the same machine as the central app?  If so, did you set the IP address on the scouting instance to 127.0.0.1 in the preferences?  The default configuration these days is now assuming a physical external scouting tablet.  If you want to sync on the same machine, you must tell the scouting program that the central IP address is 127.0.0.1.

**Comment by AarushPalve** [comment]
Yes, I tried to run the scouting app on the same machine as the central app. I didn't set the IP to 127.0.0.1 and based on the error message it seems the IP was set to 168.1.1.0 Thanks for the help.
-Aarush
