### ISSUE TITLE
No DNP for picklist

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#46]
Ability to mark a team as DNP, have their color turn red and have them moved to the bottom of the picklist

**Comment by sjcbulldog** [comment]
I am not sure why this makes sense.  You can already move a team to the bottom and they will stay there.  I am assuming that DNP means 'did not play' but this adds very little value to me.  If this is not true, convince me :)

**Comment by AarushPalve** [comment]
DNP is do not pick, and I personally haven’t seen any teams without a DNP. DNP can also indicate which teams our coach didn’t like working with.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
