### ISSUE TITLE
Can't Adjust Dimensions of Sidebar In XeroScout On Tablets Unless Using Mouse

### ISSUE THREAD

**Issue by FoodIsLogical** [sjcbulldog/elescout#49]
Tried: Adjusting the width of the sidebar on the left where you can view and enter different matches both with and without mouse. 
           Most scouters just use the touch screen but some use their own mouse.
What Happened: Couldn't adjust anything without the mouse, but could easily drag the side of sidebar to be wider using mouse.
Expected: Can adjust dimensions of sidebar using just your finger as easily as when using a mouse.

**Comment by sjcbulldog** [comment]
This is possible, I did it, but finding the range of pixels where it will work with your finger on a tablet it nearly impossible.  I will find  a better solutions.

**Comment by sjcbulldog** [comment]
I am pushing this to the next release because I don't have a tablet to test with and I wanted to get the other features out to you two.  I will fix this before the season and have some good ideas, but I need a tablet to test.

**Comment by sjcbulldog** [comment]
Ok, what I am going to do is that if you put a finger on the screen and hold it for 3 seconds, it will popup window with arrows that allows you to change the boundary between the left and right windows more easily.  The 'X' will close this popup.

I want to improve this more, but for now it is good enough to play with.
