### ISSUE TITLE
Above image counters and booleans

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#5]
When I add an image to the scouting form I want to be able to have an +- incrementor be set on top of the image but have the textbox that displays its value at another location. For the Booleans, they should be set on top of the image but be opaque so Scouters can see the image below

**Comment by sjcbulldog** [comment]
This will be handled as part of an image based section.  The sections (tabs) that exist prior to version 2.0.6 are based on HTML controls.  They are layed out in a flow, so there is not a lot of control on how they are layed out.

In 2.0.6, there can be an image backed section and on this kind of section there is an up/down control  Since we draw this on a canvas ourselves, we have exact control.  For now, the up/down has a vertical stack of +/#/-, where # is the number.  I will look at specifying the # value at a different X,Y location in a future version.

**Comment by sjcbulldog** [comment]
Booleans do not currently have a title when placed in an image.  They are drawn as a box with an internal cross if it is true.  The idea is that these should be placed in the picture in a way where it is obvious what they are.  For instance, in this year, the box should completed surround a note to indicate the note is collected.  For the up/down, there are regions for + and - that increment and decrement the value with the value displayed in one of two place.  If the number section is given, it describes where the number is displayed and can be anywhere on the background image.  If the number section is not given, then the number goes between the + and - boxes.

`
                   {
                        "tag" : "auto_speaker",
                        "name" : "autoSpeaker",
                        "type" : "updown",
                        "minimum" : 0,
                        "maximum" : 40,
                        "red" : {
                            "position" : {
                                "x" : 4.0,
                                "y" : 18.21875
                            },
                            "size" : {
                                "width" : 4.0,
                                "height" : 8.0
                            },
                            "number" : {
                                "position" : {
                                    "x" : 4.0,
                                    "y" : 14.2
                                },
                                "size" : {
                                    "width" : 2.0,
                                    "height" : 2.0
                                },
                                "font" : "96px serif"
                            }
                        },
                        "blue" : {
                            "position" : {
                                "x" : 2.0,
                                "y" : 18.21875
                            },
                            "size" : {
                                "width" : 4.0,
                                "height" : 8.0
                            },
                            "number" : {
                                "position" : {
                                    "x" : -1.2,
                                    "y" : 20
                                },
                                "size" : {
                                    "width" : 2.0,
                                    "height" : 2.0
                                },
                                "font" : "96px serif"
                            }                            
                        }
                    }
`

**Comment by sjcbulldog** [comment]
Closed per the previous comment.
