### ISSUE TITLE
Autonomous Note Selection Ability Messed Up After Changing Width of Sidebar In XeroScout

### ISSUE THREAD

**Issue by FoodIsLogical** [sjcbulldog/elescout#50]
Tried: As of now, the adjustment of the sidebar dimensions are restricted to mouse usage. After using my own mouse and stretching the sidebar (to be both wider and narrower) on a tablet, I found I could not easily click the red/green boxes representing auto notes on the visual of the field without spamming them. 

What Happened: I tried clicking using both the mouse and my finger, but it seemed 90% of the time I could not select notes on the field after messing with the sidebar. Every other element involved in scouting seemed to work just fine though (counters, true/falses).

Expected: After adjusting the sidebar, the auto notes can be selected like normal without unnecessary repeat clicks.

**Comment by sjcbulldog** [comment]
The issue seems to be if the graphical scouting form is resized, it loses the tie between what is displayed and where you click.  If you resized the side bar switched away from that form and to another, did it work?

**Comment by sjcbulldog** [comment]
As expected, this was an issue with resizing the image in the scouting form window.  This has been fixed and will be released in 2.0.14.

**Comment by FoodIsLogical** [comment]
Oh yeah, I forgot to mention that the field visualizer does get resized no matter which way you pull the sidebar, but sounds good that it'll get fixed. Thanks!
