### ISSUE TITLE
Adding "Clear all" feature to teams list and match schedule

### ISSUE THREAD

**Issue by FoodIsLogical** [sjcbulldog/elescout#9]
Not sure if there's a way to do this already, but a "clear all" feature would help with not having to manually delete each team or match one by one if the wrong list/schedule was imported when making a new event.

**Comment by sjcbulldog** [comment]
I have added the Delete All Teams, Delete All Matches buttons to the Edit Teams and Edit Matches screens.  It will be in the next 2.0.7 version of this program.  However, just so you know, if you are in the Edit Teams or Edit Matches screens, your changes do not get committed until you hit the Save button.  If instead, you hit the Cancel button, all of your changes are dropped and you go back to the way things were before you hit Edit Teams or Edit Matches.  So, hitting cancel is another way to get what you want.

**Comment by sjcbulldog** [comment]
Fixed per the previous comment.
